-- MySQL Script generated by MySQL Workbench
-- Sun Dec 20 19:42:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema truyum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema truyum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `truyum` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `truyum` ;

-- -----------------------------------------------------
-- Table `truyum`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`menu_item` (
  `menu_id` BIGINT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `active` VARCHAR(3) NOT NULL,
  `date_of_launch` DATE NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `free_delivery` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `truyum`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`user` (
  `user_id` BIGINT NOT NULL,
  `user_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `truyum`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`cart` (
  `cart_user_id` BIGINT NOT NULL,
  `cart_menu_id` BIGINT NOT NULL,
  INDEX `fk_cart_menu_item_idx` (`cart_menu_id` ASC),
  INDEX `fk_cart_user1_idx` (`cart_user_id` ASC),
  CONSTRAINT `fk_cart_menu_item`
    FOREIGN KEY (`cart_menu_id`)
    REFERENCES `truyum`.`menu_item` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`cart_user_id`)
    REFERENCES `truyum`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
